title: "My Minimal Jekyll Blog"

# No gem-based theme:
theme: null

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules"
  - ".gitignore"
  - ".github"

plugins: []

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: katex
